version: "3.8"

services:
  postgres:
    env_file:
      - .env
    image: postgres:latest
    environment:
      POSTGRES_HOST: localhost
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d postgres" ]
      interval: 5s
      timeout: 5s
      retries: 3
    volumes:
      - ./scripts/sql:/docker-entrypoint-initdb.d
      - postgres-data:/var/lib/postgresql/data
    restart: always
    networks:
      - my_network

  app:
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c "./main -config=./cmd/config/config.yml"
    volumes:
      - ./logs/app:/app/logs/app
    ports:
      - "8001:8001"
    networks:
      - my_network
    restart: always
    depends_on:
      - postgres

volumes:
  postgres-data:

networks:
  my_network:
